#!/bin/bash
set -e

echo "╔════════════════════════════════════════════════════════╗"
echo "║      IAgo - RENDER DEPLOYMENT READY                    ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Tudo pronto para deploy no Render!"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📋 CHECKLIST PRÉ-DEPLOY:"
echo ""
echo "   ✅ GitHub Pages Workflow criado"
echo "   ✅ Dockerfile multi-stage otimizado"
echo "   ✅ render.yaml blueprint configurado"
echo "   ✅ .dockerignore para build rápido"
echo "   ✅ docs/index.html pronto"
echo "   ✅ Git commit enviado"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🚀 DEPLOY NO RENDER (3 PASSOS):"
echo ""
echo "PASSO 1: Abra no navegador"
echo "   → https://render.com/dashboard"
echo ""
echo "PASSO 2: Clique 'New' → 'Web Service'"
echo "   Preencha:"
echo "   - Repository: aniversarioYago/IAgo"
echo "   - Branch: main"
echo "   - Name: iago-backend"
echo "   - Environment: Docker"
echo "   - Instance Type: Free"
echo ""
echo "PASSO 3: Environment Variables"
echo "   Clique 'Add Secret File' ou 'Advanced' e adicione:"
echo ""
echo "   KEY: GEMINI_API_KEY"
echo "   VALUE: <SUA_GEMINI_API_KEY>"
echo ""
echo "   KEY: PORT"
echo "   VALUE: 8080"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "⏱️  Tempo de build: ~5-10 minutos"
echo ""
echo "Após concluir, Render exibirá uma URL tipo:"
echo "   https://iago-backend-xxxxx.onrender.com"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✅ VALIDAR DEPLOY"
echo ""
echo "Quando Render terminar, execute:"
echo ""
echo "   curl https://iago-backend-xxxxx.onrender.com/health"
echo ""
echo "Deve retornar: ok"
echo ""
echo "Teste chat:"
echo ""
echo '   curl -X POST https://iago-backend-xxxxx.onrender.com/api/chat \'
echo "     -H 'Content-Type: application/json' \\"
echo '     -d '"'"'{"message":"Oi"}'"'"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📱 DEPOIS: Atualizar Android/Web URLs"
echo ""
echo "Se sua URL do Render for diferente de iago-backend.onrender.com:"
echo ""
echo "1. Edite: composeApp/build.gradle.kts"
echo "   Mude: .orElse(\"https://sua-render-url.onrender.com\")"
echo ""
echo "2. Edite: docs/index.html"
echo "   Mude: window.IAGO_BACKEND_URL = \"https://sua-render-url.onrender.com\""
echo ""
echo "3. Push:"
echo "   git add -A && git commit -m 'chore: update Render backend URL' && git push"
echo ""
echo "GitHub Pages web será recompilada automaticamente!"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""

